# Generated by Django 4.1 on 2023-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='Class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
